spring:
  profiles:
    active:
    - dev

---
server:
  port: 8091

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/maas_user?useSSL=false&serverTimezone=UTC&characterEncoding=utf8&useUnicode=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: admin
    type: com.alibaba.druid.pool.DruidDataSource    #当前数据源操作类型
    dbcp2:
      min-idle: 5                                   #数据库连接池的最小维持连接数
      initial-size: 5                               #初始化连接数
      max-total: 5                                  #最大连接数
      max-wait-millis: 200                          #等待连接获取的最大超时时间
  profiles: dev   ##开发环境
  application:
  application:
    name: microservicecloud-provider                  #微服务架构中对外暴露的微服务名

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml  #Mybatis配置文件所在
  mapper-locations: classpath:mybatis/mapper/*.xml    #类表关系映射表
  type-aliases-package: com.haylion.he.entity.User    #类表关系映射类

eureka:
  client: #客户端注册进Eureka服务列表内
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/ #集群下的配置
  instance:
    instance-id: microservicecloud-provider-he-8091 #自定义服务注册中心的显示名称
    prefer-ip-address: true #访问路径可以显示IP地址

info:
  app.name: haylion-microservicecloud
  company.name: www.haylion.com
  
  
  
---
server:
  port: 8091

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/maas_user?useSSL=false&serverTimezone=UTC&characterEncoding=utf8&useUnicode=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: admin
    type: com.alibaba.druid.pool.DruidDataSource    #当前数据源操作类型
    dbcp2:
      min-idle: 5                                   #数据库连接池的最小维持连接数
      initial-size: 5                               #初始化连接数
      max-total: 5                                  #最大连接数
      max-wait-millis: 200                          #等待连接获取的最大超时时间
  profiles: dev   ##开发环境
  application:
    name: microservicecloud-provider                  #微服务架构中对外暴露的微服务名

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml  #Mybatis配置文件所在
  mapper-locations: classpath:mybatis/mapper/*.xml    #类表关系映射表
  type-aliases-package: com.haylion.he.entity.User    #类表关系映射类

eureka:
  client: #客户端注册进Eureka服务列表内
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/ #集群下的配置
  instance:
    instance-id: microservicecloud-provider-he-8091 #自定义服务注册中心的显示名称
    prefer-ip-address: true #访问路径可以显示IP地址

info:
  app.name: haylion-microservicecloud
  company.name: www.haylion.com
  
  